## Runs Postgres in Docker
## Creates DB games_db with user/pass postgres/postgres
## Exposes it on localhost:5432

services:
  postgres:
    image: postgres:16
    container_name: nest_games_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: games_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
